### ISSUE TITLE
Invalid syntax errors with Python 3.7

### ISSUE THREAD

**Issue by russkel** [kepstin/regainer#1]
Hi,

async and await were made reserved keywords in Python 3.7 which means lines like 804 and 839 throw syntax errors.

I haven't done any work with asyncio otherwise I'd submit a PR.

Russ

**Comment by kepstin** [comment]
Hmm. I'll look into this - I'm still using 3.6 as my system python, so I haven't hit this issue yet. It's kind of annoying that they made a backwards incompatible change here.

I suspect I can fix this either in a forward-looking way (python 3.7+ only) by using the new async/await syntax, or get it working with older pythons as well by switching to the `@coroutine` decorator and using `yield from` instead.

**Comment by kepstin** [comment]
Turned out to be an easier fix than I thought! The `async` function just got renamed to `ensure_future` back in python 3.4; I switched to the newer function name and everything should work fine now.

**Comment by russkel** [comment]
Good to know. Thanks for fixing.
