### ISSUE TITLE
Can regainer tag multiple albums at once?

### ISSUE THREAD

**Issue by denppa** [kepstin/regainer#10]
I have my library organized like so:
```
Music/Aritists/Album/Tracks.flac
```
Would passing `~/Music` as the directory argument enable album replay gain even though the `Artists` folder level is in between them?

**Comment by kepstin** [comment]
regainer does not currently support recursively working on tracks in a directory - you need to specify a list of individual files.

For example, you might run a command like `regainer Music/Artists/Album/*.flac` to calculate replaygain for a single album. You can do multiple albums in a single command by using the `-a` argument between lists of files to start a new album, but for your case I'd actually recommend creating a shell script loop, like:

```bash
for albumdir in Music/*/* ; do regainer -a "$albumdir"/*.flac ; done
```

Support for passing directories as arguments is being tracked as #4
