### ISSUE TITLE
Peak values over 1.0

### ISSUE THREAD

**Issue by maszaa** [kepstin/regainer#8]
Why does for example foobar2000 report that some tracks whose replay gain has been calculated with Regainer have album and/or track peaks over 1.0? The audio format is integer PCM (16 and 24 bit) so that shouldn't be technically possible. Are the gains calculated in floating point and stored in that representation?

**Comment by kepstin** [comment]
The peak values are actually the "true peak" value as defined by the R.128 specification. It's the maximum level of the analogue signal represented by the digital data, which can (and does) extend above the full scale of integer pcm "in between" the sample points. (The way ffmpeg's implementation measures this is by resampling to a much higher rate and measuring the peak there).

Note also that lossy codecs like aac, opus, mp3, can be decoded directly to floating point, and are able to represent samples above the maximum that integer pcm can hold.
